apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: {{ include "generic-kargo-pipeline.projectName" . | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" . | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" . | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  promotionPolicies:
    - stage: {{ .Values.pipeline.stages.prepareRelease.name | quote }}
      autoPromotionEnabled: {{ .Values.pipeline.stages.prepareRelease.autoPromotionEnabled }}
    - stage: {{ .Values.pipeline.stages.dev.name | quote }}
      autoPromotionEnabled: {{ .Values.pipeline.stages.dev.autoPromotionEnabled }}
    - stage: {{ .Values.pipeline.stages.integration.name | quote }}
      autoPromotionEnabled: {{ .Values.pipeline.stages.integration.autoPromotionEnabled }}
    - stage: {{ .Values.pipeline.stages.preProduction.name | quote }}
      autoPromotionEnabled: {{ .Values.pipeline.stages.preProduction.autoPromotionEnabled }}
    - stage: {{ .Values.pipeline.stages.production.name | quote }}
      autoPromotionEnabled: {{ .Values.pipeline.stages.production.autoPromotionEnabled }}
