{{- if and .Values.chartGit.repository.username .Values.chartGit.repository.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-kargo-pipeline.chartGitSecretName" . | quote }}
  namespace: {{ include "generic-kargo-pipeline.projectName" . | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" . | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.chartGit.repository.username | quote }}
  password: {{ .Values.chartGit.repository.password | quote }}
{{- end }}
{{- if and .Values.developersGit.repository.username .Values.developersGit.repository.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-kargo-pipeline.developersGitSecretName" . | quote }}
  namespace: {{ include "generic-kargo-pipeline.projectName" . | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" . | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.developersGit.repository.username | quote }}
  password: {{ .Values.developersGit.repository.password | quote }}
{{- end }}
