{{- include "generic-kargo-pipeline.validateValues" . -}}
{{- $componentDefaults := .Values.sources.componentDefaults -}}
{{- $hasEnabledComponents := false -}}
{{- range .Values.sources.components }}
{{- $component := mergeOverwrite (deepCopy $componentDefaults) . -}}
{{- if $component.enabled -}}
{{- $hasEnabledComponents = true -}}
{{- end -}}
{{- end }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ include "generic-kargo-pipeline.normalizeName" .Values.warehouse.name | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" . | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" . | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  interval: {{ .Values.warehouse.interval | quote }}
  freightCreationPolicy: {{ .Values.warehouse.freightCreationPolicy | quote }}
  subscriptions:
{{- if not (or .Values.sources.deploymentGit.subscription.enabled $hasEnabledComponents) }}
    []
{{- end }}
{{- if .Values.sources.deploymentGit.subscription.enabled }}
    - git:
        repoURL: {{ .Values.sources.deploymentGit.repository.url | quote }}
        branch: {{ .Values.sources.deploymentGit.branches.source | quote }}
        commitSelectionStrategy: {{ default "NewestFromBranch" .Values.sources.deploymentGit.subscription.commitSelectionStrategy | quote }}
        {{- with .Values.sources.deploymentGit.subscription.discoveryLimit }}
        discoveryLimit: {{ . }}
        {{- end }}
        {{- with .Values.sources.deploymentGit.subscription.includePaths }}
        includePaths:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sources.deploymentGit.subscription.excludePaths }}
        excludePaths:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- range .Values.sources.components }}
{{- $component := mergeOverwrite (deepCopy $componentDefaults) . -}}
{{- if $component.enabled }}
    - image:
        repoURL: {{ $component.image.repository | quote }}
        imageSelectionStrategy: {{ default "NewestBuild" $component.image.selectionStrategy | quote }}
        {{- with $component.image.allowedTags }}
        allowTags: {{ . | quote }}
        {{- end }}
        {{- with $component.image.semverConstraint }}
        semverConstraint: {{ . | quote }}
        {{- end }}
        {{- if hasKey $component.image "strictSemvers" }}
        strictSemvers: {{ $component.image.strictSemvers }}
        {{- end }}
        {{- with $component.image.discoveryLimit }}
        discoveryLimit: {{ . }}
        {{- end }}
{{- end }}
{{- end }}
