apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ include "generic-kargo-pipeline.fullname" . | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" . | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" . | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  subscriptions:
    {{- if .Values.chartGit.subscription.enabled }}
    - git:
        repoURL: {{ .Values.chartGit.repository.url | quote }}
        branch: {{ .Values.chartGit.branches.source | quote }}
        commitSelectionStrategy: {{ default "NewestFromBranch" .Values.chartGit.subscription.commitSelectionStrategy | quote }}
        {{- with .Values.chartGit.subscription.discoveryLimit }}
        discoveryLimit: {{ . }}
        {{- end }}
        {{- with .Values.chartGit.subscription.includePaths }}
        includePaths:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.chartGit.subscription.excludePaths }}
        excludePaths:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}
    {{- range .Values.artifact.components }}
    - image:
        repoURL: {{ .image.repository | quote }}
        imageSelectionStrategy: {{ default "NewestBuild" .image.selectionStrategy | quote }}
        {{- with .image.allowedTags }}
        allowTags: {{ . | quote }}
        {{- end }}
        {{- with .image.semverConstraint }}
        semverConstraint: {{ . | quote }}
        {{- end }}
        {{- with .image.discoveryLimit }}
        discoveryLimit: {{ . }}
        {{- end }}
    {{- end }}
