apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-kargo-pipeline.chartGitSecretName" . | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" . | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" . | nindent 4 }}
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: {{ .Values.sources.chartGit.repository.url | quote }}
  username: {{ default "" .Values.sources.chartGit.repository.username | quote }}
  password: {{ default "" .Values.sources.chartGit.repository.password | quote }}
