{{- if and .Values.sources.deploymentGit.repository.username .Values.sources.deploymentGit.repository.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-kargo-pipeline.deploymentGitSecretName" . | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" . | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" . | nindent 4 }}
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: {{ .Values.sources.deploymentGit.repository.url | quote }}
  username: {{ .Values.sources.deploymentGit.repository.username | quote }}
  password: {{ .Values.sources.deploymentGit.repository.password | quote }}
{{- end }}
