{{- $defaults := include "generic-kargo-pipeline.componentDefaults" . | fromYaml -}}
{{- range .Values.sources.components }}
{{- $component := mergeOverwrite (deepCopy $defaults) . -}}
{{- if and $component.enabled $component.qaGit $component.qaGit.repository }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-kargo-pipeline.componentQaGitSecretName" $component | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" $ | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" $ | nindent 4 }}
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: {{ $component.qaGit.repository.url | quote }}
  username: {{ default "" $component.qaGit.repository.username | quote }}
  password: {{ default "" $component.qaGit.repository.password | quote }}
{{- end }}
{{- end }}
