{{- $builtInComponentDefaults := include "generic-kargo-pipeline.componentDefaults" . | fromYaml -}}
{{- $componentDefaults := mergeOverwrite (deepCopy $builtInComponentDefaults) (default dict .Values.sources.componentDefaults) -}}
{{- range .Values.sources.components }}
{{- $component := mergeOverwrite (deepCopy $componentDefaults) . -}}
{{- if $component.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-kargo-pipeline.componentDevGitSecretName" $component | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" $ | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" $ | nindent 4 }}
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: {{ $component.developerGit.repository.url | quote }}
  username: {{ default "" $component.developerGit.repository.username | quote }}
  password: {{ default "" $component.developerGit.repository.password | quote }}
{{- end }}
{{- end }}
