{{- range .Values.sources.components }}
{{- if and .enabled .git.repository.username .git.repository.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-devGit" .name | include "generic-kargo-pipeline.normalizeName" | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" $ | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" $ | nindent 4 }}
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: {{ .git.repository.url | quote }}
  username: {{ .git.repository.username | quote }}
  password: {{ .git.repository.password | quote }}
{{- end }}
{{- end }}
