{{- range $name, $service := .Values.services }}
{{- $auth := default dict $service.authentication -}}{{- $type := default "none" $auth.type -}}
{{- if and $service.endpoint (ne $type "none") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-kargo-pipeline.httpServiceSecretName" $name | quote }}
  labels:
    {{- include "generic-kargo-pipeline.labels" $ | nindent 4 }}
    {{- include "generic-kargo-pipeline.applicationLabels" $ | nindent 4 }}
    kargo.akuity.io/cred-type: generic
type: Opaque
stringData:
  type: {{ $type | quote }}
  {{- if eq $type "basic" }}
  username: {{ $auth.username | quote }}
  password: {{ $auth.password | quote }}
  headerName: Authorization
  authorization: {{ printf "Basic %s" (printf "%s:%s" $auth.username $auth.password | b64enc) | quote }}
  headerValue: {{ printf "Basic %s" (printf "%s:%s" $auth.username $auth.password | b64enc) | quote }}
  {{- else if eq $type "apiKey" }}
  headerName: {{ $auth.headerName | quote }}
  prefix: {{ default "" $auth.prefix | quote }}
  key: {{ $auth.key | quote }}
  headerValue: {{ printf "%s%s" (ternary (printf "%s " $auth.prefix) "" (not (empty $auth.prefix))) $auth.key | quote }}
  {{- end }}
{{- end }}{{- end }}
